DROP TABLE IF EXISTS weather;

CREATE TABLE weather (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  temperature INTEGER,
  humidity INTEGER ,
  light INTEGER,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
